### ISSUE TITLE
Nat Data vs Postpay Plan Data - not displaying correctly

### ISSUE THREAD

**Issue by jeremysherriff** [jordan-thoms/2Degrees-Toolbox#2]
Hi Jords, I'm not sure if this is to do with me having two types of data plan, or the fact that I have more plan items to display overall, but either way the widget (2x1) doesn't display the postpay data plan.  Probably easiest if I send you some screen shots - how best to do that?

Cheers,
Jeremy

**Comment by jordan-thoms** [comment]
Hi

I'm working on an update at the moment (done, just testing) which will not
display the 0 values on the widget - which might help. It will be based just
on having too many items.

Screenshots would be useful - Unfortunately there is not a very easy way to
get these on android. Probably the easiest for a non-rooted phone is to
install the android developer tools, and use DDMS on your computer to take
the screenshot.

Cheers,
Jordan

**Comment by jordan-thoms** [comment]
Can you test this with the new 1.5 version?

**Comment by jeremysherriff** [comment]
Closing as long dead.
