### ISSUE TITLE
Crash on refresh

### ISSUE THREAD

**Issue by axllent** [jordan-thoms/2Degrees-Toolbox#7]
Since about 2 or 3 days ago,  the app crashes every time it tries to refresh in either the main app or widget. I've uninstalled and reinstalled the app, but that doesn't help. The app opens, but soon after clicking the refresh button it'll force close. 

Please let me know if I can provide any more info to help get it working again? :-)

**Comment by jordan-thoms** [comment]
I have just released an update which should resolve this. I don't live in NZ anymore so I don't use the app myself

**Comment by axllent** [comment]
Wow, that was quick! The update hasn't come through yet on my phone, but I'll report as soon as it's done,  thanks.

**Comment by axllent** [comment]
Sweet, confirmed fixed! Thanks Jordan for sorting this out so fast, despite not using this app yourself any more. Really appreciated!
